# stacks-signer hacknet config
stacks_private_key = "$SIGNER_PRIVATE_KEY"
node_host = "$STACKS_NODE_HOST"
endpoint = "$STACKS_SIGNER_ENDPOINT"
network = "testnet"
auth_password = "12345"
db_path = "/data/signer/stacks-signer.sqlite"
metrics_endpoint = "0.0.0.0:9153"
