[node]
working_dir = "/data/chainstate"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "$BOOTSTRAP_NODE"
name = "follower"

use_test_genesis_chainstate = true
pox_sync_sample_secs = 0
wait_time_for_blocks = 0
wait_time_for_microblocks = 0
mine_microblocks = false
microblock_frequency = 1000

[connection_options]
auth_token = "12345"
private_neighbors = true

[burnchain]
pox_prepare_length = $POX_PREPARE_LENGTH
pox_reward_length = $POX_REWARD_LENGTH
peer_port = $BITCOIN_PEER_PORT
rpc_port = $BITCOIN_RPC_PORT
chain = "bitcoin"
mode = "nakamoto-neon"
poll_time_secs = 1
magic_bytes = "T3"
### bitcoind-regtest connection info
peer_host = "$BITCOIN_PEER_HOST"
timeout = 30

[[burnchain.epochs]]
epoch_name = "1.0"
start_height = 0

[[burnchain.epochs]]
start_height = $STACKS_20_HEIGHT
epoch_name = "2.0"

[[burnchain.epochs]]
start_height = $STACKS_2_05_HEIGHT
epoch_name = "2.05"

[[burnchain.epochs]]
start_height = $STACKS_21_HEIGHT
epoch_name = "2.1"

[[burnchain.epochs]]
start_height = $STACKS_22_HEIGHT
epoch_name = "2.2"

[[burnchain.epochs]]
start_height = $STACKS_23_HEIGHT
epoch_name = "2.3"

[[burnchain.epochs]]
start_height = $STACKS_24_HEIGHT
epoch_name = "2.4"

[[burnchain.epochs]]
start_height = $STACKS_25_HEIGHT
epoch_name = "2.5"

[[burnchain.epochs]]
start_height = $STACKS_30_HEIGHT
epoch_name = "3.0"

[[burnchain.epochs]]
start_height = $STACKS_31_HEIGHT
epoch_name = "3.1"

[[burnchain.epochs]]
start_height = $STACKS_32_HEIGHT
epoch_name = "3.2"

[[ustx_balance]]
address = "ST2SBXRBJJTH7GV5J93HJ62W2NRRQ46XYBK92Y039" # Deployer Account
amount = 10000000000000000

[[ustx_balance]]
address = "ST24VB7FBXCBV6P0SRDSPSW0Y2J9XHDXNHW9Q8S7H" # Signer 1 Account
amount = 10000000000000000

[[ustx_balance]]
address = "ST2XAK68AR2TKBQBFNYSK9KN2AY9CVA91A7CSK63Z" # Signer 2 Account
amount = 10000000000000000

[[ustx_balance]]
address = "ST1J9R0VMA5GQTW65QVHW1KVSKD7MCGT27X37A551" # Signer 3 Account
amount = 10000000000000000

[[ustx_balance]]
address = "ST1YEHRRYJ4GF9CYBFFN0ZVCXX1APSBEEQ5KEDN7M" # Stacker 1
amount = 10000000000000000

[[ustx_balance]]
address = "ST1WNJTS9JM1JYGK758B10DBAMBZ0K23ADP392SBV" # Stacker 2
amount = 10000000000000000

[[ustx_balance]]
address = "ST1MDWBDVDGAANEH9001HGXQA6XRNK7PX7A7X8M6R" # Stacker 3
amount = 10000000000000000

[[ustx_balance]]
# This is a 2-3 multi-sig address controlled using the above three
# addresses. The resulting multi-sig address below was created using the SignerWallet struct.
address = "SN3R84XZYA63QS28932XQF3G1J8R9PC3W76P9CSQS"
amount = 10000000000000000

[[ustx_balance]]
address = "ST3497E9JFQ7KB9VEHAZRWYKF3296WQZEXBPXG193" # Demo principal
amount = 10000000000000000
