[node]
name = "$MINER_NAME"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
prometheus_bind = "0.0.0.0:9153"
data_url = "http://$STACKS_NODE_IP:20443"
p2p_address = "$STACKS_NODE_IP:20443"
working_dir = "/data/chainstate"
bootstrap_node = "$BOOTSTRAP_NODE"
seed = "$MINER_SEED"
local_peer_seed = "$MINER_SEED"
miner = true
stacker = true
wait_time_for_microblocks = 0
mine_microblocks = false
use_test_genesis_chainstate = true
pox_sync_sample_secs = 0
wait_time_for_blocks = 200
microblock_frequency = 1000

fault_injection_block_push_fail_probability = $BLOCK_PUSH_FAIL_PROBABILITY

[miner]
first_attempt_time_ms = 180_000
subsequent_attempt_time_ms = 360_000
microblock_attempt_time_ms = 10
mining_key = "$MINER_SEED"
activated_vrf_key_path = "/data/chainstate/saved_vrf_key.json"
block_reward_recipient = "$REWARD_RECIPIENT"

[connection_options]
public_ip_address = "$STACKS_NODE_IP:20444"
auth_token = "12345"
timeout = 15
connect_timeout = 15
handshake_timeout = 15
idle_timeout = 15
dns_timeout = 15
private_neighbors = true

[burnchain]
rpc_port = $BITCOIN_RPC_PORT
peer_port = $BITCOIN_PEER_PORT
pox_prepare_length = $POX_PREPARE_LENGTH
pox_reward_length = $POX_REWARD_LENGTH
chain = "bitcoin"
mode = "nakamoto-neon"
poll_time_secs = 1
magic_bytes = "T3"
burn_fee_cap = 20_000
peer_host = "$BITCOIN_PEER_HOST"
username = "$BITCOIN_RPC_USER"
password = "$BITCOIN_RPC_PASS"
wallet_name = "$BITCOIN_WALLET"

# Add stacks-signer as an event observer
[[events_observer]]
endpoint = "$SIGNER_HOST:$SIGNER_PORT"
events_keys = ["stackerdb", "block_proposal", "burn_blocks"]
timeout_ms = 10_000

[[burnchain.epochs]]
epoch_name = "1.0"
start_height = 0

[[burnchain.epochs]]
start_height = $STACKS_20_HEIGHT
epoch_name = "2.0"

[[burnchain.epochs]]
start_height = $STACKS_2_05_HEIGHT
epoch_name = "2.05"

[[burnchain.epochs]]
start_height = $STACKS_21_HEIGHT
epoch_name = "2.1"

[[burnchain.epochs]]
start_height = $STACKS_22_HEIGHT
epoch_name = "2.2"

[[burnchain.epochs]]
start_height = $STACKS_23_HEIGHT
epoch_name = "2.3"

[[burnchain.epochs]]
start_height = $STACKS_24_HEIGHT
epoch_name = "2.4"

[[burnchain.epochs]]
start_height = $STACKS_25_HEIGHT
epoch_name = "2.5"

[[burnchain.epochs]]
start_height = $STACKS_30_HEIGHT
epoch_name = "3.0"

[[burnchain.epochs]]
start_height = $STACKS_31_HEIGHT
epoch_name = "3.1"

[[burnchain.epochs]]
start_height = $STACKS_32_HEIGHT
epoch_name = "3.2"

[[ustx_balance]]
address = "ST2SBXRBJJTH7GV5J93HJ62W2NRRQ46XYBK92Y039" # Deployer Account
amount = 10000000000000000

[[ustx_balance]]
# This is a 2-3 multi-sig address controlled using the above three
# addresses. The resulting multi-sig address below was created using the SignerWallet struct.
address = "SN3R84XZYA63QS28932XQF3G1J8R9PC3W76P9CSQS"
amount = 10000000000000000

[[ustx_balance]]
address = "ST24VB7FBXCBV6P0SRDSPSW0Y2J9XHDXNHW9Q8S7H" # Signer 1 Account
amount = 10000000000000000

[[ustx_balance]]
address = "ST2XAK68AR2TKBQBFNYSK9KN2AY9CVA91A7CSK63Z" # Signer 2 Account
amount = 10000000000000000

[[ustx_balance]]
address = "ST1J9R0VMA5GQTW65QVHW1KVSKD7MCGT27X37A551" # Signer 3 Account
amount = 10000000000000000

[[ustx_balance]]
address = "ST1YEHRRYJ4GF9CYBFFN0ZVCXX1APSBEEQ5KEDN7M" # Stacker 1
amount = 10000000000000000

[[ustx_balance]]
address = "ST1WNJTS9JM1JYGK758B10DBAMBZ0K23ADP392SBV" # Stacker 2
amount = 10000000000000000

[[ustx_balance]]
address = "ST1MDWBDVDGAANEH9001HGXQA6XRNK7PX7A7X8M6R" # Stacker 3
amount = 10000000000000000

[[ustx_balance]]
address = "ST332DWHNM323264X869MKXFZABSE5WZ60EA07TJ1" # Tester 1
amount = 10000000000000000

[[ustx_balance]]
address = "ST2FY5WGSFA209NFHDT08NCB8Y9J3P1H19YR2D674" # Tester 2
amount = 10000000000000000

[[ustx_balance]]
address = "ST3SW0AXHXFDHGQY2XMMDHN6T7VPY395WS7ZRGQCD" # Tester 3
amount = 10000000000000000
